
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  # disable animations on CI device
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # unlock device
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck